### PR TITLE
brewery: add type, type id, and contact

### PR DESCRIPTION
**Pull request by djensen47**
This PR partially addresses #8 by adding contact info, brewery type, and brewery type id.

### CODE REVIEW

**Comment by djensen47** [comment]
@mdlayher It looks like the build failing independent of the changes in the PR.

The goveralls command seems to be failing because there is no $COVERALLS_TOKEN env var defined.

**Comment by mdlayher** [comment]
Yep, sorry about that. I haven't used coveralls in ages because I don't find the coverage metric to be entirely useful.

Mind rebasing on master and re-pushing?

**Comment by mdlayher** [comment]
Failing CI is due to unrelated changes.  I'll fix. LGTM, thanks.

**Comment by djensen47** [comment]
👍 Excellent. Thanks!

**Pull request merged**
